version: '3'

services:
  timescale:
    image: "ghcr.io/pmoura-dev/hauto.timescale:0.1"
    container_name: hauto.timescale
    restart: always
    ports:
      - ${TIMESCALE_PORT}:${TIMESCALE_PORT}
    networks:
      - hauto
  
  rabbitmq:
    image: "ghcr.io/pmoura-dev/hauto.rabbitmq:0.1"
    container_name: hauto.rabbitmq
    restart: always
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}
      - ${RABBITMQ_MQTT_PORT}:${RABBITMQ_MQTT_PORT}
    networks:
      - hauto
  
  transaction-service:
    image: "ghcr.io/pmoura-dev/hauto.transaction-service:0.1"
    container_name: hauto.transaction-service
    restart: always
    environment:
      - DB_HOST=hauto.timescale
      - RABBITMQ_HOST=hauto.rabbitmq
      - APP_PORT=${TRANSACTION_SERVICE_PORT}
    networks:
      - hauto
  
  device-gateway:
    image: "ghcr.io/pmoura-dev/hauto.device-gateway:0.1"
    container_name: hauto.device-gateway
    restart: always
    environment:
      - RABBITMQ_HOST=hauto.rabbitmq
      - TRANSACTION_SERVICE_HOST=hauto.transaction-service
      - TRANSACTION_SERVICE_PORT=${TRANSACTION_SERVICE_PORT}
    networks:
      - hauto

  api-gateway:
    image: "ghcr.io/pmoura-dev/hauto.api-gateway:0.1"
    container_name: hauto.api-gateway
    restart: always
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    environment:
      - RABBITMQ_HOST=hauto.rabbitmq
      - TRANSACTION_SERVICE_HOST=hauto.transaction-service
      - TRANSACTION_SERVICE_PORT=${TRANSACTION_SERVICE_PORT}
    networks:
      - hauto

networks:
  hauto: