version: '3'

services:
  timescale:
    image: "ghcr.io/pmoura-dev/hauto.timescale:0.1"
    container_name: hauto.timescale
    restart: always
    ports:
      - ${TIMESCALE_PORT}:${TIMESCALE_PORT}
    networks:
      - hauto
  
  rabbitmq:
    image: "ghcr.io/pmoura-dev/hauto.rabbitmq:0.1"
    container_name: hauto.rabbitmq
    restart: always
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}
    networks:
      - hauto
  
  transaction-service:
    image: "ghcr.io/pmoura-dev/hauto.transaction-service:0.1"
    container_name: hauto.transaction-service
    restart: always
    ports:
      - ${TRANSACTION_SERVICE_PORT}:${TRANSACTION_SERVICE_PORT}
    environment:
      - DB_HOST=hauto.timescale
      - RABBITMQ_HOST=hauto.rabbitmq
    networks:
      - hauto

networks:
  hauto: