version: '3'

services:

  database:
    image: "ghcr.io/pmoura-dev/hauto.database:1.0"
    container_name: hauto.database
    env_file:
      - database.env
    ports:
      - "5432:5432"
    networks:
      - hauto

  device-registry:
    image: "ghcr.io/pmoura-dev/hauto.device-registry:1.0"
    container_name: hauto.device-registry
    env_file:
      - device-registry.env
    ports:
      - "8080:8080"
    networks:
      - hauto
    links:
      - database

networks:
  hauto: